# Generated by Django 3.2.13 on 2022-11-04 06:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_comment_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='phoneNumber',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='?([0-9]{3,4})-?([0-9]{3,4})-?([0-9]{4})')]),
        ),
    ]
