# Generated by Django 3.2.13 on 2022-11-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_comment_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tag',
            field=models.CharField(choices=[('morning', '아메추'), ('lunch', '점메추'), ('dinner', '저메추'), ('midnight_snack', '야메추')], max_length=32, verbose_name='태그명'),
        ),
    ]
